Sphinx
dasha-zdrogova/spbusearch pull request #2
Opened 2023-11-08 20:46 UTC by olya-antre

В ocr_files.py только функции для извлечения текста из доков, в data_based.py подключение базы данных, создание таблицы и добавление записей с файлами из папки files, созданной после использования парсера.

2023-11-18 20:46 UTC, MFattakhov requested changes
https://github.com/dasha-zdrogova/spbusearch/blob/9b668d5d4292907c58094bc51b93c03bf4678914/data_base.py#L18-L22
Давай сделаем это функцией, которая будет создавать таблицу только если такой нет

Кажется чтобы создать если такой еще нет нужно `CREATE TABLE IF NOT EXISTS ...` просто сделать

2023-11-20 19:42 UTC, MFattakhov requested changes
хочу вот такое в этом файле видеть

```python
from dataclasses import dataclass

@dataclass
class Match:
    url: str
    text: str

def get_matches(search_str: str) -> list[Match]: ...
```

2023-12-05 23:50 UTC, olya-antre commented
fixed code for database

2023-12-06 21:51 UTC, MFattakhov commented on src/lib/data_base.py
> +            create_table_query = "CREATE TABLE IF NOT EXISTS files (id int AUTO_INCREMENT, file_name varchar(400), URL varchar(400), content longtext, PRIMARY KEY(id));"
В примерах мантикоры типы text для поиска полнотекстового
И string для короткого текста без индексирования

2023-12-07 17:59 UTC, closed without merging